"""Auth services package."""

from app.auth.services.jwt import (  # noqa: F401
    create_access_token,
    create_refresh_token,
    decode_token,
    get_jwks,
    is_jti_revoked,
    revoke_jti,
    verify_token,
)
from app.auth.services.api_keys import (  # noqa: F401
    ALLOWED_SCOPES as API_KEY_ALLOWED_SCOPES,
    check_rate_limit,
    generate_api_key,
    hash_api_key,
    validate_rate_limit,
    validate_scopes,
)
from app.auth.services.oauth import (  # noqa: F401
    PROVIDER_CONFIGS,
    build_authorization_url,
    exchange_code_for_tokens,
    find_or_create_user,
    generate_code_challenge,
    generate_code_verifier,
    generate_state_token,
    get_state_store,
    get_user_info,
    store_state,
    validate_state,
)
from app.auth.services.anti_bot import (  # noqa: F401
    REPUTATION_PENALTY,
    STRICT_THRESHOLD,
    adjust_reputation,
    check_fingerprint_mismatch,
    check_rapid_account_creation,
    check_refresh_anomaly,
    generate_fingerprint,
    generate_fingerprint_from_request,
    get_effective_rate_limit,
    is_strict_mode,
    record_account_creation,
    verify_turnstile,
)

__all__ = [
    "API_KEY_ALLOWED_SCOPES",
    "PROVIDER_CONFIGS",
    "ALLOWED_SCOPES",
    "REPUTATION_PENALTY",
    "STRICT_THRESHOLD",
    "adjust_reputation",
    "build_authorization_url",
    "check_fingerprint_mismatch",
    "check_rapid_account_creation",
    "check_rate_limit",
    "check_refresh_anomaly",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "exchange_code_for_tokens",
    "find_or_create_user",
    "generate_api_key",
    "generate_code_challenge",
    "generate_code_verifier",
    "generate_fingerprint",
    "generate_fingerprint_from_request",
    "generate_state_token",
    "get_effective_rate_limit",
    "get_jwks",
    "get_state_store",
    "get_user_info",
    "hash_api_key",
    "is_jti_revoked",
    "is_strict_mode",
    "record_account_creation",
    "revoke_jti",
    "store_state",
    "validate_rate_limit",
    "validate_scopes",
    "validate_state",
    "verify_turnstile",
    "verify_token",
]
